# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/disk/Sipi/Linux/HarrisRelease/Harris3D-Cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/disk/Sipi/Linux/HarrisRelease/Harris3D-Cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/disk/Sipi/Linux/HarrisRelease/Harris3D-Cpp/CMakeFiles /media/disk/Sipi/Linux/HarrisRelease/Harris3D-Cpp/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/disk/Sipi/Linux/HarrisRelease/Harris3D-Cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Harris3D-Cpp_demo

# Build rule for target.
Harris3D-Cpp_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Harris3D-Cpp_demo
.PHONY : Harris3D-Cpp_demo

# fast build rule for target.
Harris3D-Cpp_demo/fast:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/build
.PHONY : Harris3D-Cpp_demo/fast

# target to build an object file
HarrisDetector.o:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/HarrisDetector.o
.PHONY : HarrisDetector.o

# target to preprocess a source file
HarrisDetector.i:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/HarrisDetector.i
.PHONY : HarrisDetector.i

# target to generate assembly for a file
HarrisDetector.s:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/HarrisDetector.s
.PHONY : HarrisDetector.s

# target to build an object file
Mesh.o:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/Mesh.o
.PHONY : Mesh.o

# target to preprocess a source file
Mesh.i:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/Mesh.i
.PHONY : Mesh.i

# target to generate assembly for a file
Mesh.s:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/Mesh.s
.PHONY : Mesh.s

# target to build an object file
Properties.o:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/Properties.o
.PHONY : Properties.o

# target to preprocess a source file
Properties.i:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/Properties.i
.PHONY : Properties.i

# target to generate assembly for a file
Properties.s:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/Properties.s
.PHONY : Properties.s

# target to build an object file
Vertex.o:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/Vertex.o
.PHONY : Vertex.o

# target to preprocess a source file
Vertex.i:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/Vertex.i
.PHONY : Vertex.i

# target to generate assembly for a file
Vertex.s:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/Vertex.s
.PHONY : Vertex.s

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/main.s
.PHONY : main.s

# target to build an object file
util.o:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/util.o
.PHONY : util.o

# target to preprocess a source file
util.i:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/util.i
.PHONY : util.i

# target to generate assembly for a file
util.s:
	$(MAKE) -f CMakeFiles/Harris3D-Cpp_demo.dir/build.make CMakeFiles/Harris3D-Cpp_demo.dir/util.s
.PHONY : util.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Harris3D-Cpp_demo"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... HarrisDetector.o"
	@echo "... HarrisDetector.i"
	@echo "... HarrisDetector.s"
	@echo "... Mesh.o"
	@echo "... Mesh.i"
	@echo "... Mesh.s"
	@echo "... Properties.o"
	@echo "... Properties.i"
	@echo "... Properties.s"
	@echo "... Vertex.o"
	@echo "... Vertex.i"
	@echo "... Vertex.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

